/**
 * Backfills the eight MRR-movement columns on `PartnerDailyMrrSnapshot`.
 *
 * `npm run backfill:mrr-movement` (DRY_RUN=1 to report without writing).
 *
 * By default only the eight movement columns are touched, keeping the blast
 * radius to the columns that are actually empty. `FULL=1` additionally
 * refreshes every other column — see that flag's note for when that is the
 * right call. Either way `updateMany` on the unique key rather than `update`,
 * so a day with no existing row is a no-op instead of a throw: the row SET is
 * left exactly as the snapshot job built it, only its contents change.
 *
 * Safe to re-run — every column is a pure function of immutable facts, the same
 * property the snapshot itself relies on.
 */
import { prisma } from "../app/lib/db.server";
import {
  historiesFromFacts,
  resolveOfferCadencePins,
  loadLiveDiscountChecks,
} from "../app/lib/shopify/partner-mrr.server";
import { buildDailySnapshotRows } from "../app/lib/shopify/partner-mrr-snapshot.server";

const DRY_RUN = process.env.DRY_RUN === "1";
/**
 * FULL=1 rewrites EVERY column, not just the movement eight.
 *
 * Needed because the rows on disk were built by whatever the snapshot job's
 * logic was on the day it wrote them — locally, 2026-08-18 for most of them,
 * which predates the proration, ghost-charge, stray-unfreeze and
 * replacement-cancellation fixes, so their `churnedRevenueLost` no longer
 * matches what the same code recomputes today. Leaving that
 * standing next to freshly-computed movement columns would put one row in two
 * different logic eras, so a report reading both would not add up.
 *
 * Every column is a pure function of immutable facts, so this is a
 * recomputation rather than a correction — the same property that lets the
 * snapshot be regenerated byte-for-byte at any time.
 */
const FULL = process.env.FULL === "1";
const DAY_MS = 86_400_000;
const startOfUtcDay = (at: Date) =>
  new Date(Date.UTC(at.getUTCFullYear(), at.getUTCMonth(), at.getUTCDate()));

const MOVEMENT_COLUMNS = [
  "mrrNew",
  "mrrReactivation",
  "mrrExpansion",
  "mrrContraction",
  "mrrChurn",
  "mrrFrozen",
  "mrrUnfrozen",
  "mrrEarlyPlanChange",
] as const;

const apps = await prisma.app.findMany({
  select: { id: true, name: true, billingEventsSyncedAt: true, billingSalesSyncedAt: true },
});

const grandTotals: Record<string, number> = Object.fromEntries(
  MOVEMENT_COLUMNS.map((column) => [column, 0]),
);
let rowsWritten = 0;
let rowsSkipped = 0;

for (const app of apps) {
  // Exactly the days this app already has rows for: a movement delta outside
  // that range has nowhere to land, and inventing rows here would put the
  // snapshot's own coverage bookkeeping out of step with its contents.
  const bounds = await prisma.partnerDailyMrrSnapshot.aggregate({
    where: { appId: app.id },
    _min: { snapshotDate: true },
    _max: { snapshotDate: true },
  });
  const first = bounds._min.snapshotDate;
  const last = bounds._max.snapshotDate;
  if (!first || !last) continue;

  const periodEnd = new Date(startOfUtcDay(last).getTime() + DAY_MS);
  const [events, sales] = await Promise.all([
    prisma.partnerSubscriptionEvent.findMany({
      where: { appId: app.id, occurredAt: { lt: periodEnd } },
      select: {
        appId: true,
        type: true,
        occurredAt: true,
        shopDomain: true,
        chargePlatformId: true,
        chargeName: true,
        amount: true,
        currencyCode: true,
        billingOn: true,
        test: true,
      },
      orderBy: [{ chargePlatformId: "asc" }, { occurredAt: "asc" }],
    }),
    prisma.partnerSubscriptionSaleFact.findMany({
      where: { appId: app.id, occurredAt: { lt: periodEnd } },
      select: {
        appId: true,
        chargePlatformId: true,
        occurredAt: true,
        billingInterval: true,
        grossAmount: true,
        currencyCode: true,
      },
      orderBy: [{ chargePlatformId: "asc" }, { occurredAt: "asc" }],
    }),
  ]);
  if (events.length === 0) continue;

  const offerPins = await resolveOfferCadencePins(events, sales);
  const liveDiscountChecks = await loadLiveDiscountChecks([app.id]);
  const histories = historiesFromFacts(events, sales, offerPins, liveDiscountChecks);

  const days: Date[] = [];
  for (
    let day = startOfUtcDay(first);
    day.getTime() <= startOfUtcDay(last).getTime();
    day = new Date(day.getTime() + DAY_MS)
  ) {
    days.push(day);
  }

  const { rows } = buildDailySnapshotRows({
    appId: app.id,
    appName: app.name,
    events,
    sales,
    histories,
    days,
    builtFromEventsSyncedAt: app.billingEventsSyncedAt,
    builtFromSalesSyncedAt: app.billingSalesSyncedAt,
  });

  const appTotals: Record<string, number> = Object.fromEntries(
    MOVEMENT_COLUMNS.map((column) => [column, 0]),
  );
  let written = 0;
  let skipped = 0;

  for (const row of rows) {
    const movement = Object.fromEntries(
      MOVEMENT_COLUMNS.map((column) => [column, row[column]]),
    ) as Record<(typeof MOVEMENT_COLUMNS)[number], number>;
    for (const column of MOVEMENT_COLUMNS) {
      appTotals[column]! += movement[column];
      grandTotals[column]! += movement[column];
    }
    // Every column zero is the overwhelmingly common day; there is nothing to
    // write and the column default already says so.
    const moved = MOVEMENT_COLUMNS.some((column) => movement[column] !== 0);
    if (!moved && !FULL) {
      skipped += 1;
      continue;
    }
    if (!DRY_RUN) {
      const { appId, snapshotDate, currencyCode, ...rest } = row;
      const result = await prisma.partnerDailyMrrSnapshot.updateMany({
        where: {
          appId: row.appId,
          snapshotDate: row.snapshotDate,
          currencyCode: row.currencyCode,
        },
        data: FULL ? rest : movement,
      });
      if (result.count === 0) {
        skipped += 1;
        continue;
      }
    }
    written += 1;
  }

  rowsWritten += written;
  rowsSkipped += skipped;
  const summary = MOVEMENT_COLUMNS.filter((column) => appTotals[column]! > 0)
    .map((column) => `${column.replace("mrr", "")}=${appTotals[column]!.toFixed(2)}`)
    .join(" ");
  console.log(
    `${app.name.padEnd(22)} ${String(days.length).padStart(5)} days  ` +
      `${String(written).padStart(5)} rows with movement  ${summary || "(none)"}`,
  );
}

console.log(
  `\n${DRY_RUN ? "DRY RUN — nothing written" : "written"}: ${rowsWritten} rows` +
    ` (${rowsSkipped} days with no movement, left at zero)`,
);
console.log("\nall-time totals:");
for (const column of MOVEMENT_COLUMNS) {
  console.log(`  ${column.padEnd(20)}$${grandTotals[column]!.toFixed(2)}`);
}

await prisma.$disconnect();
process.exit(0);
